[2021-08-26 01:14:17,016] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: test_dag.t1 2021-08-26T01:14:15.935777+00:00 [queued]>
[2021-08-26 01:14:17,030] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: test_dag.t1 2021-08-26T01:14:15.935777+00:00 [queued]>
[2021-08-26 01:14:17,031] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-08-26 01:14:17,032] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-08-26 01:14:17,035] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-08-26 01:14:17,075] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): t1> on 2021-08-26T01:14:15.935777+00:00
[2021-08-26 01:14:17,085] {standard_task_runner.py:52} INFO - Started process 4398 to run task
[2021-08-26 01:14:17,092] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 't1', '2021-08-26T01:14:15.935777+00:00', '--job-id', '22', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp44tmkstu', '--error-file', '/tmp/tmpbx0bvja4']
[2021-08-26 01:14:17,093] {standard_task_runner.py:77} INFO - Job 22: Subtask t1
[2021-08-26 01:14:17,154] {logging_mixin.py:104} INFO - Running <TaskInstance: test_dag.t1 2021-08-26T01:14:15.935777+00:00 [running]> on host f913d28eb98c
[2021-08-26 01:14:17,223] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dini
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2021-08-26T01:14:15.935777+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-26T01:14:15.935777+00:00
[2021-08-26 01:14:17,247] {python.py:151} INFO - Done. Returned value was: None
[2021-08-26 01:14:17,259] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=t1, execution_date=20210826T011415, start_date=20210826T011417, end_date=20210826T011417
[2021-08-26 01:14:17,288] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-26 01:14:17,304] {local_task_job.py:151} INFO - Task exited with return code 0
